
services:

  app:
    build: .
    container_name: main
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      -  .production.env
    command:
      - npm run start:prod


  db:
    image: postgres:15
    env_file:
      - .production.env
    container_name: postgres_db
    restart: always
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: